services:
  - type: web
    name: neon-space-sena
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: neon-space-db
          property: connectionString

databases:
  - name: neon-space-db
    plan: free
